title: Home Lab
background:
  image: https://images.unsplash.com/photo-1550751827-4bd374c3f58b
  opacity: 5

theme: dark
color: slate

layout:
  AI:
    style: row
    columns: 2
  Media:
    style: row
    columns: 3
  Criatividade:
    style: row
    columns: 1
  System:
    style: row
    columns: 2
  Leitura:
    style: row
    columns: 1
